#define KC_MAC_UNDO LGUI(KC_Z)
#define KC_MAC_CUT LGUI(KC_X)
#define KC_MAC_COPY LGUI(KC_C)
#define KC_MAC_PASTE LGUI(KC_V)
#define KC_PC_UNDO LCTL(KC_Z)
#define KC_PC_CUT LCTL(KC_X)
#define KC_PC_COPY LCTL(KC_C)
#define KC_PC_PASTE LCTL(KC_V)
#define ES_LESS_MAC KC_GRAVE
#define ES_GRTR_MAC LSFT(KC_GRAVE)
#define ES_BSLS_MAC ALGR(KC_6)
#define NO_PIPE_ALT KC_GRAVE
#define NO_BSLS_ALT KC_EQUAL
#define LSA_T(kc) MT(MOD_LSFT | MOD_LALT, kc)
#define BP_NDSH_MAC ALGR(KC_8)
#define MOON_LED_LEVEL LED_LEVEL
#define MAC_SPACE_L RALT(RGUI(KC_LEFT))
#define MAC_SPACE_R RALT(RGUI(KC_RIGHT))

enum tap_dance_codes {
  DANCE_0,
};

enum custom_keycodes {
  RGB_SLD = ML_SAFE_RANGE,
  HSV_172_255_255,
  HSV_86_255_128,
  HSV_27_255_255,
  HSV_215_255_128,
  HSV_0_255_255,
  ST_LOL,
  ST_LAUNCH_BLITZ,
  ST_LAUNCH_CHROME,
  ST_LAUNCH_DISCORD,
  ST_LAUNCH_DOCKER,
  ST_LAUNCH_FINDER,
  ST_LAUNCH_IINA,
  ST_LAUNCH_LOL,
  ST_LAUNCH_LOL_COMBO_2,
  ST_LAUNCH_LOL_COMBO_3,
  ST_LAUNCH_ROBO3T,
  ST_LAUNCH_SEQUELP,
  ST_LAUNCH_SLACK,
  ST_LAUNCH_SPOTIFY,
  ST_LAUNCH_SYSTEM_P,
  ST_LAUNCH_TELEGRAM,
  ST_LAUNCH_TERMINAL,
  ST_LAUNCH_VIVALDI,
  ST_LAUNCH_WHATSAPP,
  ST_MACRO_0,
  ST_MACRO_1,
  ST_MACRO_2,
  ST_MACRO_3,
  ST_MACRO_4,
  ST_MACRO_5,
  ST_MACRO_6,
  ST_TMUX_W
};
